#!/bin/sh -ex

INSTALLER_DIR=/tmp
TARGET_DIR=/var/www/opm
APP_OWNER=wsgi
APP_GROUP=www-data
LOG_DIR=/var/log/opm
VENV=$TARGET_DIR/virtualenv
NER_DIR=$TARGET_DIR
NLTK_DATA_DIR=$VENV/nltk_data
APP_DIR=$TARGET_DIR/app
cd $INSTALLER_DIR
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main" | tee /etc/apt/sources.list.d/adoptopenjdk.list

install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}
install adoptopenjdk-8-hotspot

systemctl start apache2
mkdir -p $TARGET_DIR
mkdir -p $APP_DIR
# stanford ner
wget https://nlp.stanford.edu/software/stanford-ner-4.0.0.zip
unzip stanford-ner-4.0.0.zip -d $NER_DIR
mv $NER_DIR/stanford-ner-4.0.0 $NER_DIR/stanford-ner
wget https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/tags/4.7.1.tar.gz
tar xvzf 4.7.1.tar.gz
cd 4.7.1 && ./configure --with-python=/usr/bin/python3.7
cd 4.7.1 && make
cd 4.7.1 && make install
cd 4.7.1 && make clean
echo "LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so" > /etc/apache2/mods-available/wsgi.load
wget https://github.com/Open-Prose-Metrics/open_prose_metrics_app-core/archive/refs/heads/main.zip
unzip main.zip
cp -r open_prose_metrics_app-core-main/opm/* $APP_DIR/
useradd -d $TARGET_DIR -s /bin/bash -g www-data $APP_OWNER
pip3 install --upgrade pip
python3.7 -m pip install pip
pip3.7 install virtualenv wheel
virtualenv -p python3.7 $VENV
. $VENV/bin/activate
python -m pip install -r $APP_DIR/requirements.txt
python -m nltk.downloader -d $NLTK_DATA_DIR stopwords words punkt brown vader_lexicon averaged_perceptron_tagger maxent_ne_chunker



mkdir -p $LOG_DIR
chown -R $APP_OWNER:$APP_GROUP $LOG_DIR
#chown -R $APP_OWNER:$APP_GROUP /var/log/extraeyes
chown -R $APP_OWNER:$APP_GROUP $TARGET_DIR
chmod -R g+w $TARGET_DIR


sed -i "s|{{ owner }}|$APP_GROUP|g" /etc/apache2/sites-available/opm.conf
sed -i "s|{{ group }}|$APP_GROUP|g" /etc/apache2/sites-available/opm.conf
sed -i "s|{{ app_dir }}|$APP_DIR|g" /etc/apache2/sites-available/opm.conf
sed -i "s|{{ target_dir }}|$TARGET_DIR|g" /etc/apache2/sites-available/opm.conf
sed -i "s|{{ owner }}|$APP_OWNER|g" /etc/apache2/sites-available/opm-ssl.conf
sed -i "s|{{ group }}|$APP_GROUP|g" /etc/apache2/sites-available/opm-ssl.conf
sed -i "s|{{ app_dir }}|$APP_DIR|g" /etc/apache2/sites-available/opm-ssl.conf
sed -i "s|{{ target_dir }}|$TARGET_DIR|g" /etc/apache2/sites-available/opm-ssl.conf


sed -i "s|/var/www/html/open-prose-metrics/opm|$APP_DIR|g" $APP_DIR/opm.wsgi
sed -i "s|/var/www/html/open-prose-metrics|$TARGET_DIR|g" $APP_DIR/opm.wsgi
sed -i "s|('tagger.pkl')|('$APP_DIR/tagger.pkl')|g" $APP_DIR/postagger.py
cd $APP_DIR && python postagger.py
cd $APP_DIR && python seed_database.py
chown $APP_OWNER:$APP_GROUP $APP_DIR/tagger.pkl
chown $APP_OWNER:$APP_GROUP $APP_DIR/shelve*
chmod g+w $APP_DIR/tagger.pkl
chmod g+w $APP_DIR/shelve.*
deactivate

#rm master.zip
#rm -rf /Open_Prose_Metrics-*

a2enmod wsgi
a2dissite 000-default
a2ensite opm.conf
#systemctl reload apache2
systemctl stop apache2
iptables -A INPUT -p tcp --dport 5000 -j ACCEPT
